### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yasunamiura** [kenkoba-valks/chat-space#10]
小林さん、ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**Chat-SpaceのIPアドレスをこちらに記入していただきたいです。**

該当カリキュラム
https://master.tech-camp.in/curriculums/3967#21 

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kenkoba-valks** [comment]
確認が漏れていました。以下に記載します。
＃IPアドレス
54.199.203.175

よろしくご査収ください。
